### ISSUE TITLE
version values lost

### ISSUE THREAD

**Issue by Prarewyn** [jenslody/codeblocks#1]
When reopening a project that has AV running in "Use #define" mode all version values / version.h are reset to 0 after the first compilation / opening AV dialogue.

**Comment by jenslody** [comment]
Please file a bug-rfeport on our sourceforge project site (https://sourceforge.net/p/codeblocks/tickets/) or at least pos the issue in our forum (http://forums.codeblocks.org/).
This is just a git-mirror of the main (svn-)repo.
